sudo: required
services:
  - docker

before_install:
  - docker build -t zazahan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zazahan/react-test npm test -- --coverage

after_success:
  - docker build -t zazahan/multi-client ./client
  - docker build -t zazahan/multi-nginx ./nginx
  - docker build -t zazahan/multi-server ./server
  - docker build -t zazahan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push zazahan/multi-worker
  - docker push zazahan/multi-client
  - docker push zazahan/multi-server
  - docker push zazahan/multi-nginx